askmate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from qna_app.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('qna/', include('qna_app.urls')),
    path('user/', include('user_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qna_app/urls.py
from django.contrib import admin
from django.urls import path
from qna_app.views import home, question, popular, addquestion, update_question, del_question, vote_question, add_ans, QuestionListView, add_answer, detail
app_name = 'qna'

urlpatterns = [
    path('view/', question),
    path('popular/', popular),
    path('read/', question,name='read'),
    path('add/', addquestion, name='add'),
    path('update/<int:id>/', update_question,name='update'),
    path('delete/<int:id>/', del_question, name='delete'),
    path('vote/<int:id>/', vote_question, name='vote'),
    path('answeradd/<int:id>/', add_ans, name='addans'),
    path('addanswer/<int:id>/', add_answer, name='comment'), 
    path('listview/', QuestionListView.as_view(), name='listview'),
    path('detail/<int:id>/', detail, name='detail'),
]

user_app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import loginauth, logout
app_name = 'user'

urlpatterns = [
    path('login/', loginauth, name='login'),
    path('logout/', logout, name='logout'),
]

qna_app/models.py
from django.db import models

# Create your models here.

class CategoryModel(models.Model):
    cat_title = models.CharField(max_length=120)
    cat_desc = models.TextField(max_length=255)

    def __str__(self):
        return(self.cat_title)


class QuestionModel(models.Model):
    title = models.CharField(max_length=255)
    posted_by = models.CharField(max_length=120)
    timestamp = models.DateTimeField(auto_now_add=True)
    question_desc = models.TextField()
    question_votes = models.IntegerField(default=0)
    question_img = models.ImageField(upload_to='QuestionImg', blank=True, null=True)
    category = models.ForeignKey(CategoryModel,on_delete=models.CASCADE)

    def __str__(self):
        return(self.title)


class AnswerModel(models.Model):
    ans_by = models.CharField(max_length=120)
    ans_desc = models.TextField()
    ans_votes = models.IntegerField(default=0)
    ans_timestamp = models.DateTimeField(auto_now_add=True)
    ans_img = models.ImageField(upload_to="AnswerImg", blank=True, null=True)
    is_accepted = models.BooleanField(default=0)
    question = models.ForeignKey(QuestionModel,on_delete=models.CASCADE)

    def __str__(self):
        return(self.ans_desc[:50]) + '...'

# class VotedbyModel

user_app/models.py
from django.db import models

# Create your models here.

class UserModel(models.Model):
    name = models.CharField(max_length=120)
    email = models.EmailField()
    password = models.CharField(max_length=120)
    address = models.CharField(max_length=255, null=True)
    contact = models.CharField(max_length=14, null=True)
    reputation = models.PositiveIntegerField(default=0)

    def __str__(self):
        return(self.name)

qna_app/forms.py
from django import forms 
from .models import QuestionModel, AnswerModel

class QuestionForm(forms.ModelForm):
    class Meta:
        model = QuestionModel
        fields = '__all__'

class AnswerForm(forms.ModelForm):
    class Meta:
        model = AnswerModel
        fields = '__all__'

qna_app/views.py
from django.shortcuts import render, redirect
from .models import QuestionModel, AnswerModel, CategoryModel
from qna_app.forms import QuestionForm, AnswerForm
from django.http import HttpResponse
from django.views.generic import CreateView, ListView

# Create your views here.

class QuestionListView(ListView):
    queryset = QuestionModel.objects.all()

def home(request):
    return render(request, 'home.html')

def question(requests):
    Question = QuestionModel.objects.all()
    return render(requests, 'questionmodel_list.html', {'ques':Question})

def popular(request):
    Question = QuestionModel.objects.all()
    return render(request, 'popular.html', {'ques':Question})

def addquestion(request):
    if 'id' in request.session:
        if(request.method == 'POST'):
            form = QuestionForm(request.POST, request.FILES)
            if form.is_valid():
                try:
                    form.save()
                    return redirect('qna:detail', id=id)
                except:
                    return HttpResponse('Failed')
            else:
                print(form.errors)
                return HttpResponse('Form not Valid')
        else:
            # form = QuestionForm
            category = CategoryModel.objects.all()
            return render(request, 'questionmodel_create.html', {'category':category})
    else:
        return redirect('user:login')

def update_question(request, id):
    question = QuestionModel.objects.get(id=id)
    if(request.method == 'POST'):
        form = QuestionForm(request.POST, request.FILES, instance=question)
        if form.is_valid():
            try:
                form.save()
                return redirect('qna:detail', id=id)
            except:
                return HttpResponse('Failed')
        else:
            print(form.errors)
            return HttpResponse('Form not Valid')
    else:
        form = QuestionForm(instance=question)
        return render(request, 'questionmodel_update.html', {'form':form})
    
def del_question(request, id): 
    question = QuestionModel.objects.get(id=id)
    question.delete()
    return redirect('qna:read')

def vote_question(request, id):
    question = QuestionModel.objects.get(id=id)   
    question.question_votes += 1
    question.save()
    return redirect('qna:detail', id=id)

def add_ans(request, id):
    if request.method == "POST":
        by = request.POST.get('ans_by')
        desc = request.POST.get('ans_desc')
        vote = request.POST.get('ans_votes')
        time = request.POST.get('ans_timestamp')
        img = request.POST.get('ans_img')
        question = QuestionModel.objects.get(id=id)
        comment = AnswerModel(ans_by = by, ans_desc = desc, ans_votes = vote, ans_timestamp = time, ans_img = img, question = question)
        comment.save()
        # return render(request, 'answermodel_create.html', {'answer':answer})
        return HttpResponse('success')
    else:
        form = AnswerForm()
        a = {'form':form}
        b = {'id':id}
        c = {**a, **b}
        return render(request, 'answermodel_create.html', c) 
    
def add_answer(request, id):
    question_instance = QuestionModel.objects.get(id=id) 
    # answer_instance = AnswerModel.objects.all()
    answer = request.POST.get('ans_desc') 
    comment = AnswerModel.objects.create(ans_desc = answer, question=question_instance )
    comment.save()
    return HttpResponse('commented')

def detail(request, id):
    # question = None
    # try:
    #     question = QuestionModel.objects.get(id=id)
    # except:
    #     question = []
    question = QuestionModel.objects.filter(id=id).first()
    if request.method == "POST":
        description = request.POST['answer']
        # question = id
        answer = AnswerModel(ans_desc = description, question = question)
        answer.save(force_insert=True)

    
    answers = AnswerModel.objects.filter(question=id)
    d = {
        'question':question,
        'answers':answers
    }
    return render(request, 'detail.html', d)
    

user_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from user_app.models import UserModel
from qna_app.urls import home


# Create your views here.

def loginauth(request):
    if request.method == "POST":
        e = request.POST.get('email')
        p = request.POST.get('pass')
        users = UserModel.objects.filter(email=e, password=p)
        if(users.count() > 0):
            for user in users:
                request.session['email'] = user.email
                request.session['id'] = user.id
                request.session['name'] = user.name
                return redirect('home')
        else:
            return HttpResponse('Wrong Credentials')
    else:
        return render(request, 'login.html')

def logout(request):
    request.session.flush()
    return redirect('home')

    # return HttpResponse('logged out')

qna_app/templates/answermodel_create.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    answered by: <input type="text" name="ans_by"><br><br>
    Description: <input type="text" name="ans_desc"><br><br>
    Image: <input type="file" name="ans_img"><br><br>
    <input type="hidden" name="ans_votes" value="0">
    <input type="submit" value="submit">
</form>

qna_app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>
        {% block title %}
            Hello world!
        {% endblock %}
    </title>
  </head>
  <body>
        <div class="pb-2 mt-4 mb-2 border-bottom">
          <h1>Ask<b> Mate</b></h1>
          <h6>Where you get your answers.</h6>
          {%if 'id' in request.session%}
            <h6>Welcome, {{request.session.name}}! |<a href="{%  url 'user:logout' %}">Log Out</a></h6>
          {%endif%}
          {% block login%}
          {%if 'id' not in request.session%}
            <h6>Welcome! |<a href="{%  url 'user:login' %}">Login</a></h6>
          {%endif%}
          {% endblock %}
          
        </div>
    {% block main_content %}
        <h1>Hello World!</h1>
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

qna_app/templates/detail.html
{% extends 'base.html' %}

{% block title %}
    {{question.title}}
{% endblock%}

{% block main_content %}
    <b>{{question.title}}</b> <br>
    <h5>{{question.question_desc}} </h5>
    <span style="font-size: x-small; border: 0.5px solid grey; padding: 3px; border-radius: 25px;">votes:{{question.question_votes}} </span>
    <br>
    Answers: <br>
    {% for ans in answers %}
        {{forloop.counter}}. {{ans.ans_desc}} <br>
    {% endfor %} <br>
    
    {% if 'id' in request.session %}
    <a href="{% url 'qna:update' question.id %}"><input type="button" value="update"></a>
    <a href="{% url 'qna:delete' question.id %}"><input type="button" value="delete"></a>
    <a href="{% url 'qna:vote' question.id %}"><input type="button" value="vote"></a>
    
    <br><h3>Answer this question:</h3>
    <form action="#" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Your Answer</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" name="answer" rows="3"></textarea>
            <button type="submit">Submit</button>
        </div>
    {% endif %}
    </form>
    
{% endblock %}

qna_app/templates/home.html
{% extends 'base.html' %}

{% block title %}
    AskMate | Home
{% endblock %}

{% block main_content %}
    <a class="btn btn-primary" href="{% url 'qna:read' %}" role="button">View Questions</a>
    <a class="btn btn-primary" href="{% url 'qna:add' %}" role="button">Add Questions</a>
{% endblock %}

qna_app/templates/popular.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>popular</title>
</head>
<body>
    <table>
        {% for q in ques %}
            <tr>
                <td><h3 style="margin: 0;">{{q.posted_by}} </h3> <span style="color: grey; font-size: small;">{{q.timestamp|date:'Y-M-D  h-m-s P'}}</span>
                    <br>
                    Q. {{q.question_desc|truncatechars:20}}(<i>{{q.category}}</i>)
                    <br>
                    <span style="margin-left: 18px; font-size: small; color: grey;"><i>(category:{{q.title}})</i></span>
                    {% if q.question_img != null %}
                    <br>
                    <img src='../../media/{{q.question_img}}' style="height: 100px; width: 100px;">
                    {% endif %}
                    <br>
                    <span style="font-size: x-small; border: 0.5px solid grey; padding: 3px; border-radius: 25px;">votes:{{q.question_votes}} </span>
                    <hr>
                </td>
                <!-- <td><b>{{q.posted_by}}</b></td> -->
                <!-- <td>{{q.category}}</td> -->
            </tr>
        {% endfor %}
    </table>
</body>
</html>

qna_app/templates/qnaapp/questionmodel_list.html
{{object_list}}

qna_app/templates/questionmodel_create.html
<form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        Title : <input type="text" name="title"><br><br>
        posted by: <input type="text" name="posted_by"><br><br>
        Description: <input type="text" name="question_desc"><br><br>
        Image: <input type="file" name="question_img"><br><br>
        Category: 
        <select name="category">
            {% for cat in category %}
                <option value="{{cat.id}}">{{cat.cat_title}}</option>
            {% endfor %}
        </select><br><br>
        <input type="hidden" name="question_votes" value="0">
        <input type="submit" value="submit">
        
</form>

qna_app/templates/questionmodel_list.html
{% extends 'base.html' %}

{% block main_content %}
<!-- <a href="{% url 'user:logout' %}" style="float: right;">logout</a><br> -->

{% for q in ques%}
    {{ forloop.counter }}. <a href="{% url 'qna:detail' q.id %}">{{q.question_desc}} </a><br>
    <!-- <br>
    <form method="POST" action="{% url 'qna:comment' q.id %}">
        <textarea name="ans_desc" cols="30" rows="2" ></textarea>
        <button>comment</button>
    </form>
    <a href="{% url 'qna:update' q.id %}"><input type="button" value="update"></a>
    <a href="{% url 'qna:delete' q.id %}"><input type="button" value="delete"></a>
    <a href="{% url 'qna:vote' q.id %}"><input type="button" value="vote"></a>
    <br> -->
    <span style="font-size: x-small; border: 0.5px solid grey; padding: 3px; border-radius: 25px;">votes:{{q.question_votes}} </span>
    <hr>
{% endfor %}
{% endblock%}



<!-- <!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
   
</body>
</html> -->

qna_app/templates/questionmodel_update.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="update">
</form>

qna_app/templates/questions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    these are questions
    {% for q in ques %}
        <h1>{{q.title}}</h1>
        <h2>{{q.question_desc}}</h2>
        <img src="../../media/{{q.question_img}}" style="height:100px; width:100px;" alt="">
        <br>
    {%endfor%}
</body>
</html>

user_app/templates/login.html
{% extends 'base.html'%}

{% block title%}
    AskMate | login
{% endblock %}

{% block main_content %}
{% block login%}
{% endblock %}
    <form action="" method="POST">
        {% csrf_token %}
        <div class="login text-center">
        <h1>Login to your account</h1></div><br>
        Email:<br>
        <input type="email" class="form-control" name="email">
        <br>
        Password:<br>
        <input type="password" class="form-control" name="pass">
        <!-- <small><a href="#">Forgot password</a></small> -->
        <br><br>
        <button type="submit" name="login" class="btn btn-success">Login</button>
    </form>
{% endblock %}
   